### model
model_name_or_path: saves-0.5/llama2-7b-wo3layers-joint-0.25
dst_mode: joint
dst_ratio: 0.25
### method
finetuning_type: full

### dataset
task: mmlu_test  # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: fewshot
lang: en
n_shot: 5

### output
save_dir: saves-0.5/llama2-7b-wo3layers-joint-0.25-mmlu

### eval
batch_size: 4
